### PR TITLE
import: fix import paths to local repo

### PR DESCRIPTION
**Pull request by hunchback**
To test changes:

```
export GO111MODULE=on
make fmt
make all
make test
```

### CODE REVIEW

**Comment by dubek** [comment]
Looks good to me. Can we please add a CI check which runs the unit-tests (`make test`) ?

**Comment by dubek** [comment]
Of course this PR conflicts with #1 and #2 (due to path changes `*/mod` → `*/pkg` ).

**Comment by safchain** [comment]
need to be rebased

**Comment by hunchback** [comment]
rebased

**Comment by hunchback** [comment]
> Of course this PR conflicts with #1 and #2 (due to path changes `*/mod` → `*/pkg` ).

@lebauce - are you handling?

**Comment by hunchback** [comment]
@safchain / @lebauce - please merge

**Pull request merged**
