### PR TITLE
secadvisor: Add retries when fetching cluster IPs from analyzer

### PR DESCRIPTION
**Pull request by dubek**
In `subnet_autodiscovery` classifier mode, if the skydive-flow-exporter
starts before the analyzer is ready, the exporter will exit immediately
with error when trying to fetch the topology from the analyzer.

This commit adds 10 retries (with 1 second delay interval between
retries) before actually exiting with an error.

### CODE REVIEW

**Comment by hunchback** [comment]
> In `subnet_autodiscovery` classifier mode, if the skydive-flow-exporter
> starts before the analyzer is ready, the exporter will exit immediately
> with error when trying to fetch the topology from the analyzer.
> 
> This commit adds 10 retries (with 1 second delay interval between
> retries) before actually exiting with an error.

a 10s delay may not be enough on some systems, I would rather retry indefenetly (never existing) but emitting log messages which can be viewed via `kubectl logs`

Additionally you may want extend this approach to also address failing to connect the WebSocket client to the Analyzer.

**Comment by hunchback** [comment]
> > In `subnet_autodiscovery` classifier mode, if the skydive-flow-exporter
> > starts before the analyzer is ready, the exporter will exit immediately
> > with error when trying to fetch the topology from the analyzer.
> > This commit adds 10 retries (with 1 second delay interval between
> > retries) before actually exiting with an error.
> 
> Why not remain running and keep trying emitting a log message when failing (but never exiting)

**Comment by dubek** [comment]
I looked at the websocket client code (skydive's `websocket/client.go` in the `Start()` function) and indeed it retries indefinitely with 1 second delay retries. I also tried this experimentally.

Given that, I think I'll indeed follow your advice and make the retries indefinite (with log messages).

More generally (but not for now), I think a better approach is fail fast and crash on error, and let Kubernetes bring up a new instance. This doesn't work for us now because we run the exporter as a container inside the analyzer pod, and I'm not sure we can control the restarting behaviour of individual containers inside pods. It might be better to run the exporter as a separate pod, but there might be also disadvantages (network traffic if scheduled to another worker node?).

**Comment by dubek** [comment]
Force-pushed with indefinite retries; also changed logging level from Warning to Error (because it needs attention - system won't work without this succeeding).

**Pull request merged**
